name: Metrics

on:
  schedule:
    - cron: "20 3 * * *"   # roda 1x/dia
  workflow_dispatch:        # permite rodar manualmente

permissions:
  contents: write           # precisa escrever o SVG no repositório

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: adautovazjr
          filename: github-metrics.svg
          template: classic
          base: ""                       # (opcional) não mostrar seções básicas
          config_timezone: America/Sao_Paulo

          # GARANTIR que salve no branch certo e faça commit
          output_action: commit
          committer_branch: main         # se seu branch padrão for "master", troque aqui

          # Linguagens por commits recentes
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_days: 90
          plugin_languages_recent_load: 500
          plugin_languages_limit: 10
          plugin_languages_details: percentage
          plugin_languages_threshold: 0%
