name: Metrics

on:
  schedule:
    - cron: "20 3 * * *"   # Atualiza 1x/dia
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # para gravar o SVG no repo
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: adautovazjr             # seu usuário
          template: classic
          filename: github-metrics.svg  # arquivo que o README referenciará
          base: ""                      # não mostrar seções básicas (opcional)

          # Línguas por commits recentes
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_days: 90      # janela de tempo
          plugin_languages_recent_load: 500     # quantos eventos/commits ler
          plugin_languages_limit: 10            # top N
          plugin_languages_details: percentage  # mostra %
          plugin_languages_threshold: 0%        # não esconder línguas pequenas
          config_timezone: America/Sao_Paulo
